name: Build and Push Docker Image to GCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code  #
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker to use Google Cloud credentials
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev


      # - name: Build Docker image #
      #   run: |   
      #     IMAGE_NAME="europe-west1-docker.pkg.dev/buzzwatch-422510/mutualism/mutualism-frontend"  
      #     TAG="2" 
      #     docker build -t "$IMAGE_NAME:$TAG" frontend

      # - name: Push Docker image to GCR
      #   run: |
      #     IMAGE_NAME="europe-west1-docker.pkg.dev/buzzwatch-422510/mutualism/mutualism-frontend"  
      #     TAG="2" 
      #     docker push "$IMAGE_NAME:$TAG"

      # - name: 'deploy'
      #   uses: 'google-github-actions/deploy-cloudrun@v2'
      #   with:
      #     service: 'mutualism-frontend'
      #     region: 'europe-west1'
      #     image: 'europe-west1-docker.pkg.dev/buzzwatch-422510/mutualism/mutualism-frontend:2'

      - name: Start VM instance
        run: |
          gcloud compute instances start sonarqube --zone=europe-west1-d


      - name: Get VM public IP
        id: get_ip
        run: |
          IP_ADDRESS=$(gcloud compute instances describe sonarqube \
                       --zone=europe-west1-d \
                       --format='get(networkInterfaces[0].accessConfigs[0].natIP)')
          echo "SONAR_HOST_URL=http://$IP_ADDRESS:9000" >> $GITHUB_ENV

      # - name: Wait for SonarQube to be available
      #   run: |
      #     echo "Waiting for SonarQube to be available at $SONAR_HOST_URL"
          
      #     while : ; do
      #       RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $SONAR_HOST_URL || true) 
            
      #       if [[ "$RESPONSE" == "200" ]]; then
      #         echo "SonarQube is now available!"
      #         break
      #       else
      #         echo "SonarQube not available yet. Response code: $RESPONSE. Retrying..."
      #         sleep 5
      #       fi
      #     done
      #     sleep 20
      #   env:
      #       SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}

      # - name: run test and coverage
      #   run: |
      #     cd frontend
      #     npm install
      #     npm test

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }} 

      - uses: phwt/sonarqube-quality-gate-action@v1
        id: quality-gate-check
        with:
          sonar-project-key: Mutualism
          sonar-host-url: ${{ env.SONAR_HOST_URL }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          github-token: ${{ secrets.PAT_TOKEN }}
        env:
          SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }} 

      - name: Output result
        run: |
          echo "${{ steps.quality-gate-check.outputs.project-status }}"
          echo "${{ steps.quality-gate-check.outputs.quality-gate-result }}"

      # - name: Get Coverage
      #   id: get_coverage
      #   run: |
      #     response=$(curl -u ${{ secrets.SONAR_TOKEN }}: "${{env.SONAR_HOST_URL}}/api/measures/component?component=Mutualism&metricKeys=coverage,code_smells,vulnerabilities,bugs" -o sonar_report.json)
      #     echo "::set-output name=coverage::$(echo $response | jq -r '.component.measures[0].value')"
      #   env:
      #     SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }} 
      
      # - name: show coverage
      #   run: |
      #     cat sonar_report.json
        
      # - name: Send Analysis Results to Discord
      #   run: |
      #     REPORT_CONTENT=$(cat sonar_report.json)
          
      #     curl -X POST -H "Content-Type: application/json" \
      #     -d "{\"content\": \"SonarQube Analysis Results: $REPORT_CONTENT\"}" \
      #     https://discord.com/api/webhooks/1303310756162441256/J76trMLyIuixm-9RCkJULw46GnqcppkVnGB_jxTKdEkCdspuW7RFU7BiZxx-M9-xrm47

          
      # - name: Stop VM instance
      #   run: |
      #     gcloud compute instances stop sonarqube --zone=europe-west1-d

